In [42]:
import numpy as np
import pandas as pd
import seaborn as sns
import os

from sklearn.ensemble import IsolationForest
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

In [43]:
df = pd.read_csv(os.getcwd() + "/Cleansed/df_all.csv", index_col=0)


In [39]:
df

0      1    2      3  4    5 type
0         7.807692  13620  209  48087  5  487   -1
1        19.015152  19230   70  32811  0    1   -1
2        15.759324  18684  325  35438  0   40   -1
3        26.557692  26131  207  32149  0    0   -1
4        16.011072 -20262   31  45696  0    0   -1
...            ...    ...  ...    ... ..  ...  ...
4139142   3.332168   1721  220  50387  0    0  neg
4139143  25.295455  25413  289  53996  0    1  neg
4139144   7.221445 -15181  329  28100  0    0  neg
4139145   0.576923   2772  141  10252  0    0  neg
4139146   0.483683  -2201   72  39317  0    0  neg

[4139147 rows x 7 columns]

In [44]:
le = preprocessing.LabelEncoder()
X = df.iloc[:,:-1].values
y = le.fit_transform(df.iloc[:,-1])
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [46]:
isoforest = IsolationForest(n_estimators = 100)
isoforest.fit(X_train)

IsolationForest()

In [50]:
y_pred =  isoforest.predict(X_test)

In [62]:
for i in range(len(y_pred)):
    if y_pred[i] == -1:
        y_pred[i] == 0

In [61]:
# average anomaly score
isoforest.decision_function(X_test)

array([0.07953334, 0.12171945, 0.02138179, ..., 0.07537465, 0.07807452,
       0.12659785])

In [73]:
cm= confusion_matrix(y_test,y_pred)
print(cm)
print("Accuracy:", list(y_pred).count(1)/y_pred.shape[0])

[[     0      0      0]
 [140017      0 541981]
 [ 11663      0 134169]]
Accuracy: 0.8167739753330998


In [82]:
count = 0 
for i in range(len(y_test)):
    if (y_pred[i] == y_test[i]):
        count += 1
print(count)
print(count/len(y_test))

134169
0.16207313095683895
