In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import os

from sklearn.ensemble import IsolationForest
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

In [12]:
df = pd.read_csv(os.getcwd() + "/test.csv", index_col=0)
df

peak_amplitude    integral  phase_angle  cycle_number  rise_time  \
0        -58.530580  -39.367594   -55.401772    269.148817 -58.205164   
1        -28.500573 -148.857548   -26.708968    261.213459 -28.575458   
2        -28.180181  -21.407660   -27.556941    133.389387 -28.098914   
3        -54.233660  -43.214370   -51.485712    257.398127 -54.306465   
4        -42.682480  -53.075543   -39.978731    221.014658 -42.647502   
..              ...         ...          ...           ...        ...   
349      -61.604708  -48.346873   -59.938636    292.980809 -61.589891   
350      -87.779407   65.405605   -86.670108    284.525324 -87.692400   
351      -74.319017  -20.659884   -72.685107    314.769197 -73.395289   
352      -37.902093  214.927648   -36.287730    -65.515717 -37.683912   
353      -56.217655  176.028575   -55.604411     48.317363 -56.283577   

     pulse_width  new_feature  new_feature2  type  
0     -57.643707    -0.857386     61.550384     1  
1     -28.570913     1.141608   -335.168262     1  
2     -28.145693     1.141607   -353.942971     1  
3     -54.157919     1.090091     60.650960     1  
4     -42.630402     1.141622     21.804150     1  
..           ...          ...           ...   ...  
349   -61.500701    -0.857918     67.783329     0  
350   -87.789015    -0.858212    856.716409     0  
351   -73.709899    -0.858131    214.321018     0  
352   -37.538196     1.141570    -48.130058     0  
353   -56.240295    -0.850878     60.745154     0  

[354 rows x 9 columns]

In [13]:
le = preprocessing.LabelEncoder()
X = df.iloc[:,:-1].values
y = (df.iloc[:,-1])

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [15]:
isoforest = IsolationForest(n_estimators = 100)
isoforest.fit(X_train)

IsolationForest()

In [16]:
y_pred =  isoforest.predict(X_test)

In [17]:
pred_data = pd.DataFrame({"Predicted values":y_pred, "Actual values":y_test})
pred_data

Predicted values  Actual values
6                   1              1
140                -1              1
300                 1              0
218                 1              0
90                  1              1
..                ...            ...
318                 1              0
162                 1              0
250                 1              0
208                 1              0
63                  1              1

[71 rows x 2 columns]

In [18]:
cm= confusion_matrix(y_test,y_pred)
print(cm)

[[ 0  0  0]
 [ 4  0 32]
 [10  0 25]]


## y_pred
Isolation Tree
pos = -1
neg = 1

## y_test
Label Encoder
pos = 1
neg = 0

In [23]:
count = 0 
for i in range(len(y_test)):
    if (y_pred[i] == -1 and list(y_test[i]) == 1):
        count += 1
    elif(y_pred[i] == 1 and y_test[i] == 0):
        count +=1
print(count)
print(count/len(y_test))

KeyError: 0

In [10]:
for i in range(6):
    test = df
    test = test.drop(test.columns[i], axis=1)
    print(test.columns.values)
    le = preprocessing.LabelEncoder()

    X = test.iloc[:,:-1]
    y = le.fit_transform(test.iloc[:,-1])
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 0)
    
    isoforest = IsolationForest(n_estimators = 100)
    isoforest.fit(X_train)
    y_pred =  isoforest.predict(X_test)
    cm= confusion_matrix(y_test,y_pred)
    print(cm)
    count = 0 
    for i in range(len(y_test)):
        if (y_pred[i] == -1 and y_test[i] == 1):
            count += 1
        elif(y_pred[i] == 1 and y_test[i] == 0):
            count +=1
    print(count/len(y_test))

['integral' 'phase_angle' 'cycle_number' 'rise_time' 'pulse_width' 'type']
[[ 0  0  0]
 [ 4  0 32]
 [15  0 20]]
0.6619718309859155
['peak_amplitude' 'phase_angle' 'cycle_number' 'rise_time' 'pulse_width'
 'type']
[[ 0  0  0]
 [ 6  0 30]
 [11  0 24]]
0.5774647887323944
['peak_amplitude' 'integral' 'cycle_number' 'rise_time' 'pulse_width'
 'type']
[[ 0  0  0]
 [ 4  0 32]
 [12  0 23]]
0.6197183098591549
['peak_amplitude' 'integral' 'phase_angle' 'rise_time' 'pulse_width'
 'type']
[[ 0  0  0]
 [ 5  0 31]
 [13  0 22]]
0.6197183098591549
['peak_amplitude' 'integral' 'phase_angle' 'cycle_number' 'pulse_width'
 'type']
[[ 0  0  0]
 [ 4  0 32]
 [13  0 22]]
0.6338028169014085
['peak_amplitude' 'integral' 'phase_angle' 'cycle_number' 'rise_time'
 'type']
[[ 0  0  0]
 [ 4  0 32]
 [15  0 20]]
0.6619718309859155


## Isolation Tree Iteration Result